services:
  - type: web
    name: travelmate
    env: python
    plan: free
    region: oregon
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GEMINI_API_KEY
      - key: GOOGLE_CLIENT_ID
      - key: GOOGLE_CLIENT_SECRET
